
package universidadgrupo.vistas;


import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import universidadgrupo.accesoAdatos.*;
import universidadgrupo.entidades.*;





public class InscripcionVista extends javax.swing.JInternalFrame {
private DefaultTableModel modelo = new DefaultTableModel();
universidadgrupo.accesoAdatos.MateriaData matedata = new universidadgrupo.accesoAdatos.MateriaData();
universidadgrupo.accesoAdatos.InscripcionData indata = new universidadgrupo.accesoAdatos.InscripcionData();
universidadgrupo.accesoAdatos.AlumnoData aludata = new universidadgrupo.accesoAdatos.AlumnoData();

    /**
     * Creates new form Inscripcion
     */
    public InscripcionVista() {
        initComponents();
        llenarCombo();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SeleccioneAlumno = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        materiasNo = new javax.swing.JRadioButton();
        materiasSI = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMaterias = new javax.swing.JTable();
        anularInscripcion = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        inscribir = new javax.swing.JButton();

        setTitle("Manejo de Inscripciones");

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Formulario de Inscripcion");

        jLabel2.setText(" Alumno:");

        SeleccioneAlumno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un alumno" }));
        SeleccioneAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccioneAlumnoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Listado de Materias");

        materiasNo.setText("Materias no Inscriptas");
        materiasNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiasNoActionPerformed(evt);
            }
        });

        materiasSI.setText("Materia Inscriptas");
        materiasSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiasSIActionPerformed(evt);
            }
        });

        jTableMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jTableMaterias);

        anularInscripcion.setText("Anular Inscripción");
        anularInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anularInscripcionActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        inscribir.setText("Inscribir");
        inscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscribirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(materiasSI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(materiasNo)
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inscribir)
                .addGap(43, 43, 43)
                .addComponent(anularInscripcion)
                .addGap(73, 73, 73)
                .addComponent(salir)
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(SeleccioneAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SeleccioneAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(materiasSI)
                    .addComponent(materiasNo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inscribir)
                    .addComponent(anularInscripcion)
                    .addComponent(salir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void SeleccioneAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccioneAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeleccioneAlumnoActionPerformed

    private void materiasNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiasNoActionPerformed
        borrarFilas();
        materiasSI.setSelected(false);
        materiasNo.setSelected(true);
        anularInscripcion.setEnabled(false);
        inscribir.setEnabled(true);
        llenarTabla();
       
    }//GEN-LAST:event_materiasNoActionPerformed

    private void materiasSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiasSIActionPerformed
          borrarFilas();
        materiasSI.setSelected(true);
        materiasNo.setSelected(false);
        anularInscripcion.setEnabled(true);
        inscribir.setEnabled(false);
        llenarTabla();
    }//GEN-LAST:event_materiasSIActionPerformed

    private void inscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscribirActionPerformed
        Alumno alumnoSeleccionado = (Alumno)SeleccioneAlumno.getSelectedItem();
        
        int filasSelec=jTableMaterias.getSelectedRow();
        if(filasSelec != -1){
            int idMateria = (Integer)modelo.getValueAt(filasSelec, 0);//pongo un integer porque quiero pasarlo de Object a entero
//           
            Materia mat = new Materia();
            mat.setIdMateria(idMateria);
           
            Inscripcion insc = new Inscripcion(alumnoSeleccionado, mat, 0);
            indata.guardarInscripcion(insc);
        }else{
           JOptionPane.showMessageDialog(this, "Por favor seleccione una materia");
        }
    }//GEN-LAST:event_inscribirActionPerformed

    private void anularInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anularInscripcionActionPerformed
        Alumno alumnoSeleccionado = (Alumno)SeleccioneAlumno.getSelectedItem();
        int filasSelec=jTableMaterias.getSelectedRow();
        if(filasSelec != -1){
            int idM = (Integer)modelo.getValueAt(filasSelec, 0);
            indata.borrarInscripcionMateriaAlumno(alumnoSeleccionado.getIdAlumno(), idM);
            
        }else{
           JOptionPane.showMessageDialog(this, "Por favor seleccione una materia");
        }
    }//GEN-LAST:event_anularInscripcionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox SeleccioneAlumno;
    private javax.swing.JButton anularInscripcion;
    private javax.swing.JButton inscribir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMaterias;
    private javax.swing.JRadioButton materiasNo;
    private javax.swing.JRadioButton materiasSI;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
public void llenarCombo(){
//Guarda en la base
    for(Alumno alu:aludata.listarAlumnos()){ //LISTAR ALUMNOS
        SeleccioneAlumno.addItem(alu);
    }
}

private void llenarTabla(){
//       Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: java.lang.String cannot be cast to entidades.Alumno
                Alumno alumnoSeleccionado = (Alumno)SeleccioneAlumno.getSelectedItem();
                
        if(materiasNo.isSelected()){
           
            List<Materia> materias= indata.obtenerMateriasNOCursadas(alumnoSeleccionado.getIdAlumno());
            for(Materia m:materias){
                modelo.addRow(new Object[]{m.getIdMateria(),m.getNombre(),m.getAnioMateria()});
            }
        }else{
             
            List<Materia> materias= indata.obtenerMateriasCursadas(alumnoSeleccionado.getIdAlumno());
            for(Materia m:materias){
                modelo.addRow(new Object[]{m.getIdMateria(),m.getNombre(),m.getAnioMateria()});
            }
        }
    }

private void armarCabecera(){
    ArrayList<Object>titulo = new ArrayList();
 titulo.add("ID");
 titulo.add("Nombre");
 titulo.add("Año");
 for(Object tit:titulo){
 modelo.addColumn(tit);
 }
jTableMaterias.setModel(modelo);
 
  }

private void borrarFilas(){
  int filas=jTableMaterias.getRowCount()-1;
  for(;filas>=0;filas--){
  modelo.removeRow(filas);
  }
}
}




